// Data for the living city (src/life.js): Porto's moving transport.
//
//   node scripts/fetch-life.mjs
//
// Writes data/life.json. The alignments below are the real OSM geometry
// (Overpass, retrieved 2026-10-02, ODbL), decimated and oriented:
//
//   funicular  Funicular dos Guindais (1891, rebuilt 2004): the real
//              railway=funicular alignment, top station (Batalha) first.
//              Guindais is a single track with a mid passing loop, so the
//              two car tracks share both stations and split across the
//              middle. The split is generated by a +-1.4 m lateral offset
//              with a sin() ramp (0 at the stations, max mid-way).
//   trams      STCP Elétrico Linha 1 (Infante <-> Foz / Passeio Alegre):
//              OSM route relation 6077696, one ordered polyline along the
//              river, decimated to ~25 m.
//   cablecar   Teleférico de Gaia (2011): the two real stations (OSM
//              aerialway=station) and the gondola line between them.
//   fountains  [] (Braga's list is not generalised: the spray builder then
//              does nothing in Porto, as today).
//
// To refresh, re-derive the arrays from Overpass:
//   way["railway"="funicular"](41.138,-8.615,41.146,-8.604)
//   relation(6077696);out geom
//   way["aerialway"~"gondola|station"](41.130,-8.625,41.150,-8.595)
// Node 22, no dependencies.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'data', 'life.json');

const ORIGIN = { lat: 41.1496, lon: -8.611 }; // cities/porto.json origin
const M_PER_DEG_LAT = 110574;
const M_PER_DEG_LON = 111320;
const r6 = (v) => Math.round(v * 1e6) / 1e6;
const cos0 = Math.cos((ORIGIN.lat * Math.PI) / 180);
const dist = (a, b) => Math.hypot((a[0] - b[0]) * M_PER_DEG_LAT, (a[1] - b[1]) * M_PER_DEG_LON * cos0);
const length = (l) => l.slice(1).reduce((s, p, i) => s + dist(l[i], p), 0);

// Funicular dos Guindais: real centreline, top station first (Batalha).
const FUN_CENTER = [
  [41.143222, -8.608236], [41.142904, -8.608399], [41.142675, -8.608507], [41.142442, -8.608618],
  [41.14222, -8.608736], [41.142114, -8.608797], [41.141941, -8.608898], [41.141898, -8.608927],
  [41.141865, -8.608957], [41.141833, -8.608984], [41.141774, -8.609026], [41.141477, -8.609202],
  [41.14115, -8.609395], [41.140985, -8.609495], [41.140926, -8.609529],
];

// Tram 1: real route, Infante (east) to Passeio Alegre (Foz).
const TRAM_ROUTE = [
  [41.140553, -8.616259], [41.140594, -8.616558], [41.140711, -8.616815], [41.140962, -8.617361],
  [41.141096, -8.617664], [41.141314, -8.618143], [41.141516, -8.618593], [41.141658, -8.618873],
  [41.142191, -8.619683], [41.142366, -8.619945], [41.142517, -8.620181], [41.14272, -8.620417],
  [41.142944, -8.620653], [41.143141, -8.620852], [41.143382, -8.62116], [41.143599, -8.621532],
  [41.143778, -8.621923], [41.143907, -8.622267], [41.144001, -8.622555], [41.144115, -8.622932],
  [41.144238, -8.623315], [41.14445, -8.623997], [41.144611, -8.62451], [41.144716, -8.624863],
  [41.144822, -8.625253], [41.144847, -8.625701], [41.144835, -8.626239], [41.144819, -8.62668],
  [41.144782, -8.627175], [41.144799, -8.627682], [41.144835, -8.628094], [41.144944, -8.628435],
  [41.145051, -8.628712], [41.145193, -8.62906], [41.145505, -8.629635], [41.145643, -8.630113],
  [41.145657, -8.630465], [41.145742, -8.630771], [41.146017, -8.631104], [41.146222, -8.631275],
  [41.146384, -8.631503], [41.146566, -8.631807], [41.147038, -8.632708], [41.147179, -8.632976],
  [41.147359, -8.633313], [41.147534, -8.633651], [41.14764, -8.634033], [41.148032, -8.635346],
  [41.148135, -8.635722], [41.148223, -8.636107], [41.148311, -8.636599], [41.148394, -8.636896],
  [41.148422, -8.637223], [41.148408, -8.637526], [41.148548, -8.640063], [41.148563, -8.6404],
  [41.14849, -8.640819], [41.148264, -8.641616], [41.14819, -8.64196], [41.148143, -8.642259],
  [41.14811, -8.642583], [41.148099, -8.642962], [41.148251, -8.644223], [41.14848, -8.645928],
  [41.148522, -8.646272], [41.148538, -8.647171], [41.148539, -8.647556], [41.148396, -8.648181],
  [41.148294, -8.648527], [41.148065, -8.649167], [41.147968, -8.649455], [41.147935, -8.649822],
  [41.147986, -8.650205], [41.148047, -8.650615], [41.148137, -8.651267], [41.148205, -8.651792],
  [41.148362, -8.653004], [41.148445, -8.653333], [41.148511, -8.653739], [41.148557, -8.654071],
  [41.148531, -8.654397], [41.1472, -8.657104], [41.147025, -8.657444], [41.146865, -8.657764],
  [41.146781, -8.658106], [41.146814, -8.658433], [41.146991, -8.659396], [41.147082, -8.659887],
  [41.14718, -8.660246], [41.147337, -8.660681], [41.147472, -8.661084], [41.147562, -8.661408],
  [41.147758, -8.662404], [41.147851, -8.662883], [41.148, -8.663692], [41.148107, -8.664247],
  [41.148148, -8.664637], [41.148161, -8.665018], [41.148103, -8.665369], [41.147907, -8.665783],
  [41.147619, -8.666372], [41.147484, -8.666658], [41.147455, -8.667019], [41.147595, -8.667347],
  [41.147736, -8.667698], [41.147811, -8.667888],
];

// Teleférico de Gaia: lower (Cais de Gaia) -> upper (Jardim do Morro).
const CABLE_STATIONS = { lower: [41.137344, -8.616077], upper: [41.137887, -8.609746] };
const CABLE_LINE = [
  [41.137887, -8.609746], [41.137878, -8.60985], [41.137479, -8.614531], [41.137351, -8.615989], [41.137344, -8.616077],
];

// Offset a line laterally by offM with a sin() ramp: 0 at both ends, max at
// the middle. Turns Guindais' single track into the passing loop.
function offsetTrack(center, offM) {
  const kx = M_PER_DEG_LON * cos0;
  const kz = M_PER_DEG_LAT;
  const m = center.map((p) => ({ x: (p[1] - ORIGIN.lon) * kx, z: -(p[0] - ORIGIN.lat) * kz }));
  const cum = [0];
  for (let i = 1; i < m.length; i++) cum.push(cum[i - 1] + Math.hypot(m[i].x - m[i - 1].x, m[i].z - m[i - 1].z));
  const total = cum[cum.length - 1] || 1;
  const out = [];
  for (let i = 0; i < m.length; i++) {
    const p0 = m[Math.max(0, i - 1)];
    const p1 = m[Math.min(m.length - 1, i + 1)];
    let dx = p1.x - p0.x;
    let dz = p1.z - p0.z;
    const l = Math.hypot(dx, dz) || 1;
    dx /= l;
    dz /= l;
    const f = Math.sin(Math.PI * (cum[i] / total));
    out.push([r6(ORIGIN.lat - (m[i].z + dx * offM * f) / kz), r6(ORIGIN.lon + (m[i].x - dz * offM * f) / kx)]);
  }
  return out;
}

const tracks = [offsetTrack(FUN_CENTER, 1.4), offsetTrack(FUN_CENTER, -1.4)];
const spanM = Math.round(length(CABLE_LINE));

const out = {
  generated: new Date().toISOString().slice(0, 10),
  sources: {
    funicular: 'OSM Overpass railway=funicular (Guindais), chained; passing-loop tracks generated with a +-1.4 m lateral ramp',
    tram: 'OSM Overpass relation 6077696 (STCP Tram 1 Infante <-> Passeio Alegre), chained and decimated to 25 m',
    cablecar: 'OSM Overpass aerialway=gondola/station (Teleférico de Gaia); height gain ~60 m from terrain',
    license: 'ODbL, OpenStreetMap contributors',
  },
  funicular: {
    name: 'Funicular dos Guindais (1891, rebuilt 2004)',
    site: null,
    tracks,
    centerline: FUN_CENTER,
    lengths_m: tracks.map((tr) => Math.round(length(tr))),
    stations: { lower: FUN_CENTER[FUN_CENTER.length - 1], upper: FUN_CENTER[0] },
  },
  trams: {
    name: 'Elétrico Linha 1: Infante <-> Foz / Passeio Alegre',
    routes: [TRAM_ROUTE],
    spacing_m: 900,
    speed_mps: 6,
    source: 'STCP Tram 1 route relation, OSM 6077696',
  },
  cablecar: {
    name: 'Teleférico de Gaia (2011)',
    stations: [CABLE_STATIONS.lower, CABLE_STATIONS.upper],
    cabins: 6,
    period: 20,
    span_m: spanM,
    gain_m: 60,
    line: CABLE_LINE,
  },
  fountains: [],
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(out, null, 1) + '\n');
console.log(
  `data/life.json: ${tracks.length} funicular tracks (${out.funicular.lengths_m.join(', ')} m), ` +
    `${TRAM_ROUTE.length} tram points (${Math.round(length(TRAM_ROUTE))} m), ` +
    `cable car ${spanM} m span, ${out.cablecar.cabins} cabins`,
);
