// Data for the living city (src/life.js): Porto's moving transport.
//
//   node scripts/fetch-life.mjs
//
// Writes data/life.json. The alignments below are the real OSM geometry
// (Overpass, retrieved 2026-10-02, ODbL), decimated and oriented:
//
//   funicular  Funicular dos Guindais (1891, rebuilt 2004): the real
//              railway=funicular alignment, top station (Batalha) first.
//              Guindais is a single track with a mid passing loop, so the
//              two car tracks share both stations and split across the
//              middle. The split is generated by a +-1.4 m lateral offset
//              with a sin() ramp (0 at the stations, max mid-way).
//   trams      the three historic STCP lines - 1 (Infante <-> Passeio
//              Alegre), 18 (Clérigos <-> Passeio Alegre), 22 (Carmo <->
//              Batalha) - from OSM route relations 6077696, 15867094 and
//              2772495, ordered polylines decimated to ~25 m.
//   cablecar   Teleférico de Gaia (2011): the two real stations (OSM
//              aerialway=station) and the gondola line between them.
//   rail       Rolling stock on the Douro crossings: the Metro do Porto
//              (Linha D) across the Luís I upper deck, and CP mainline
//              trains on the Ponte de São João to Campanhã. Real OSM
//              alignments (relation 2567504, Linha do Norte ways): the
//              bridge deck height comes from data/dimensions.json (Luís I
//              upper deck 60 m, São João 66 m above the river).
//   boats      River traffic on the Douro: rabelo boats, cruisers and the
//              Gaia <-> Ribeira ferry. The alignments are authored over the
//              real river channel (checked against the OSM water in
//              scripts/smoke-life.mjs), not derived from a single OSM way.
//   fountains  [] (Braga's list is not generalised: the spray builder then
//              does nothing in Porto, as today).
//
// To refresh, re-derive the arrays from Overpass:
//   way["railway"="funicular"](41.138,-8.615,41.146,-8.604)
//   rel(6077696);out geom;  # 1;  rel(15867094); # 18;  rel(2772495); # 22
//   way["aerialway"~"gondola|station"](41.130,-8.625,41.150,-8.595)
// Node 22, no dependencies.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'data', 'life.json');

const ORIGIN = { lat: 41.1496, lon: -8.611 }; // cities/porto.json origin
const M_PER_DEG_LAT = 110574;
const M_PER_DEG_LON = 111320;
const r6 = (v) => Math.round(v * 1e6) / 1e6;
const cos0 = Math.cos((ORIGIN.lat * Math.PI) / 180);
const dist = (a, b) => Math.hypot((a[0] - b[0]) * M_PER_DEG_LAT, (a[1] - b[1]) * M_PER_DEG_LON * cos0);
const length = (l) => l.slice(1).reduce((s, p, i) => s + dist(l[i], p), 0);

// Funicular dos Guindais: real centreline, top station first (Batalha).
const FUN_CENTER = [
  [41.143222, -8.608236], [41.142904, -8.608399], [41.142675, -8.608507], [41.142442, -8.608618],
  [41.14222, -8.608736], [41.142114, -8.608797], [41.141941, -8.608898], [41.141898, -8.608927],
  [41.141865, -8.608957], [41.141833, -8.608984], [41.141774, -8.609026], [41.141477, -8.609202],
  [41.14115, -8.609395], [41.140985, -8.609495], [41.140926, -8.609529],
];

// The three historic STCP tram routes, decimated to ~25 m. Geometry is the
// ordered OSM route relation (ODbL), retrieved 2026-10-03:
//   1   relation 6077696  Infante <-> Passeio Alegre (riverside)
//   18  relation 15867094 Clerigos <-> Passeio Alegre (Campo Alegre)
//   22  relation 2772495  Carmo <-> Batalha (city centre)
const TRAM_1 = [
  [41.140553, -8.616259], [41.140594, -8.616558], [41.140711, -8.616815], [41.140962, -8.617361],
  [41.141096, -8.617664], [41.141314, -8.618143], [41.141516, -8.618593], [41.141658, -8.618873],
  [41.142191, -8.619683], [41.142366, -8.619945], [41.142517, -8.620181], [41.14272, -8.620417],
  [41.142944, -8.620653], [41.143141, -8.620852], [41.143382, -8.62116], [41.143599, -8.621532],
  [41.143778, -8.621923], [41.143907, -8.622267], [41.144001, -8.622555], [41.144115, -8.622932],
  [41.144238, -8.623315], [41.14445, -8.623997], [41.144611, -8.62451], [41.144716, -8.624863],
  [41.144822, -8.625253], [41.144847, -8.625701], [41.144835, -8.626239], [41.144819, -8.62668],
  [41.144782, -8.627175], [41.144799, -8.627682], [41.144835, -8.628094], [41.144944, -8.628435],
  [41.145051, -8.628712], [41.145193, -8.62906], [41.145505, -8.629635], [41.145643, -8.630113],
  [41.145657, -8.630465], [41.145742, -8.630771], [41.146017, -8.631104], [41.146222, -8.631275],
  [41.146384, -8.631503], [41.146566, -8.631807], [41.147038, -8.632708], [41.147179, -8.632976],
  [41.147359, -8.633313], [41.147534, -8.633651], [41.14764, -8.634033], [41.148032, -8.635346],
  [41.148135, -8.635722], [41.148223, -8.636107], [41.148311, -8.636599], [41.148394, -8.636896],
  [41.148422, -8.637223], [41.148408, -8.637526], [41.148548, -8.640063], [41.148563, -8.6404],
  [41.14849, -8.640819], [41.148264, -8.641616], [41.14819, -8.64196], [41.148143, -8.642259],
  [41.14811, -8.642583], [41.148099, -8.642962], [41.148251, -8.644223], [41.14848, -8.645928],
  [41.148522, -8.646272], [41.148538, -8.647171], [41.148539, -8.647556], [41.148396, -8.648181],
  [41.148294, -8.648527], [41.148065, -8.649167], [41.147968, -8.649455], [41.147935, -8.649822],
  [41.147986, -8.650205], [41.148047, -8.650615], [41.148137, -8.651267], [41.148205, -8.651792],
  [41.148362, -8.653004], [41.148445, -8.653333], [41.148511, -8.653739], [41.148557, -8.654071],
  [41.148531, -8.654397], [41.1472, -8.657104], [41.147025, -8.657444], [41.146865, -8.657764],
  [41.146781, -8.658106], [41.146814, -8.658433], [41.146991, -8.659396], [41.147082, -8.659887],
  [41.14718, -8.660246], [41.147337, -8.660681], [41.147472, -8.661084], [41.147562, -8.661408],
  [41.147758, -8.662404], [41.147851, -8.662883], [41.148, -8.663692], [41.148107, -8.664247],
  [41.148148, -8.664637], [41.148161, -8.665018], [41.148103, -8.665369], [41.147907, -8.665783],
  [41.147619, -8.666372], [41.147484, -8.666658], [41.147455, -8.667019], [41.147595, -8.667347],
  [41.147736, -8.667698], [41.147811, -8.667888],
];

const TRAM_18 = [
  [41.145574, -8.614826], [41.145566, -8.615129], [41.145613, -8.615506], [41.145688, -8.61586],
  [41.145822, -8.616178], [41.146005, -8.616516], [41.146197, -8.616773], [41.146373, -8.617062],
  [41.146428, -8.617367], [41.146404, -8.617702], [41.14615, -8.619561], [41.146105, -8.61989],
  [41.146056, -8.620184], [41.14602, -8.620491], [41.145995, -8.62081], [41.145859, -8.621676],
  [41.145802, -8.622099], [41.145721, -8.622892], [41.145663, -8.623588], [41.145637, -8.623898],
  [41.145613, -8.624221], [41.145583, -8.624522], [41.14548, -8.624894], [41.145347, -8.626122],
  [41.145188, -8.627788], [41.145183, -8.628094], [41.145356, -8.628366], [41.145553, -8.628538],
  [41.14572, -8.628764], [41.145888, -8.628981], [41.146396, -8.629582], [41.14642, -8.630444],
  [41.146383, -8.631082], [41.146383, -8.631386], [41.14648, -8.631657], [41.147038, -8.632708],
  [41.147179, -8.632976], [41.147359, -8.633313], [41.147534, -8.633651], [41.14764, -8.634034],
  [41.148032, -8.635346], [41.148135, -8.635722], [41.148223, -8.636107], [41.14831, -8.636599],
  [41.148394, -8.636896], [41.148422, -8.637223], [41.148408, -8.637526], [41.148548, -8.640063],
  [41.148563, -8.6404], [41.14849, -8.640819], [41.148264, -8.641616], [41.14819, -8.64196],
  [41.148143, -8.642259], [41.14811, -8.642583], [41.148099, -8.642962], [41.148251, -8.644223],
  [41.14848, -8.645928], [41.148522, -8.646272], [41.148538, -8.647171], [41.148539, -8.647556],
  [41.148396, -8.648181], [41.148294, -8.648527], [41.148065, -8.649167], [41.147968, -8.649455],
  [41.147935, -8.649822], [41.147986, -8.650205], [41.148047, -8.650615], [41.148137, -8.651267],
  [41.148205, -8.651792], [41.148362, -8.653004], [41.148445, -8.653333], [41.148511, -8.653739],
  [41.148557, -8.654071], [41.148531, -8.654396], [41.1472, -8.657104], [41.147025, -8.657444],
  [41.146865, -8.657764], [41.146781, -8.658106], [41.146814, -8.658433], [41.146991, -8.659396],
  [41.147082, -8.659887], [41.14718, -8.660246], [41.147337, -8.660681], [41.147472, -8.661084],
  [41.147562, -8.661408], [41.147758, -8.662404], [41.147851, -8.662883], [41.148, -8.663692],
  [41.148107, -8.664246], [41.148148, -8.664637], [41.14816, -8.665018], [41.148103, -8.665369],
  [41.147907, -8.665783], [41.147619, -8.666372], [41.147484, -8.666658], [41.147455, -8.667019],
  [41.147595, -8.667347], [41.147736, -8.667698], [41.147811, -8.667888],
];

const TRAM_22 = [
  [41.146679, -8.616193], [41.146374, -8.616266], [41.146088, -8.616332], [41.145822, -8.616178],
  [41.145688, -8.61586], [41.145623, -8.615566], [41.14557, -8.615236], [41.145569, -8.614906],
  [41.145585, -8.614554], [41.145769, -8.613745], [41.145841, -8.613457], [41.145937, -8.61252],
  [41.146006, -8.611783], [41.146036, -8.610999], [41.146055, -8.610654], [41.146073, -8.610306],
  [41.146097, -8.608815], [41.146105, -8.608332], [41.146122, -8.607363], [41.146066, -8.607058],
  [41.145648, -8.607257], [41.145421, -8.607335], [41.145066, -8.607091], [41.144745, -8.607179],
  [41.144485, -8.607304], [41.144218, -8.60748], [41.14371, -8.607817], [41.143472, -8.608008],
  [41.143278, -8.608175],
];

// ---- rail rolling stock (Metro do Porto Linha D; CP Linha do Norte)
// Metro do Porto Linha D across the Luís I upper deck, from the Gaia portal
// (Jardim do Morro, 41.13762,-8.60869) into São Bento (41.14469,-8.61076).
// OSM route relation 2567504 (route=light_rail, "Linha D"), ordered way
// members; the two "Ponte Luiz I" light_rail ways (31572985, 165660757)
// carry the deck. Decimated at way nodes (~15-30 m).
const METRO_D = [
  [41.136226, -8.608245], [41.1363, -8.608268], [41.136365, -8.608289],
  [41.137121, -8.608531], [41.13762, -8.608689], [41.13794, -8.60879],
  [41.138226, -8.60888], [41.138375, -8.608925], [41.138528, -8.608973],
  [41.140923, -8.609729], [41.141927, -8.610054], [41.141948, -8.610061],
  [41.142015, -8.61008], [41.142083, -8.610099], [41.142177, -8.610119],
  [41.142278, -8.610137], [41.142385, -8.610154], [41.14269, -8.610201],
  [41.142824, -8.610225], [41.142942, -8.610248], [41.143102, -8.610288],
  [41.143111, -8.610292], [41.143287, -8.610341], [41.14397, -8.610547],
  [41.144692, -8.610763],
];

// CP Linha do Norte (Via Ascendente), from General Torres (Gaia) across the
// Ponte de São João to Porto-Campanhã (41.15073,-8.58564): OSM ways
// 142939389/142939391 (Gaia approach), 142939380 (the São João main span),
// 1207413417 + 543213029 (Porto viaduct), then 1361045533..691377238 to the
// Campanhã throat. Bridge span mid at 41.1384,-8.59629 (Ponte de São João).
const CP_NORTE = [
  [41.133111, -8.60939], [41.133225, -8.608536], [41.133498, -8.606894],
  [41.133822, -8.604948], [41.134115, -8.603609], [41.134325, -8.602982],
  [41.134527, -8.602456], [41.134743, -8.601957], [41.135006, -8.601434],
  [41.135279, -8.600954], [41.135677, -8.60033], [41.136593, -8.598923],
  [41.137078, -8.598156], [41.13759, -8.597389], [41.138247, -8.596351],
  [41.139617, -8.594287], [41.140035, -8.593666], [41.140723, -8.592731],
  [41.141849, -8.591169], [41.142332, -8.590473], [41.143, -8.589485],
  [41.143084, -8.589361], [41.143738, -8.588395], [41.144147, -8.587795],
  [41.144349, -8.587502], [41.144438, -8.587371], [41.14453, -8.58723],
  [41.144632, -8.587081], [41.144801, -8.586871], [41.144949, -8.586705],
  [41.145104, -8.586557], [41.145271, -8.586409], [41.145395, -8.586308],
  [41.145588, -8.586166], [41.145845, -8.585994], [41.14601, -8.585895],
  [41.14615, -8.585825], [41.146409, -8.585674], [41.146743, -8.58548],
  [41.146826, -8.58543], [41.146986, -8.585345], [41.147035, -8.585319],
  [41.147213, -8.585227], [41.147307, -8.585188], [41.147409, -8.58515],
  [41.147609, -8.58509], [41.14771, -8.585061], [41.148749, -8.584833],
  [41.1495, -8.585], [41.15055, -8.58545], [41.15073, -8.58564],
];

const RAIL = {
  name: 'Rolling stock: Metro do Porto (Linha D) and CP mainline',
  gauge_m: 1.435,
  items: [
    {
      id: 'metro-d',
      operator: 'Metro do Porto',
      line: 'D',
      service: 'metro',
      colour: '#F9C212',
      speed_mps: 14,
      count: 2,
      cars: 3,
      bridge: { site: 'ponte-luis-i', deck_m: 60, span: [[41.13794, -8.60879], [41.14193, -8.61005]] },
      path: METRO_D,
      source: 'OSM route relation 2567504 (Metro do Porto Linha D) across the Ponte Luís I upper deck; deck 60 m (dimensions.json ponte-luis-i)',
    },
    {
      id: 'cp-norte',
      operator: 'CP',
      line: 'Norte',
      service: 'mainline',
      colour: '#C0392B',
      speed_mps: 20,
      count: 2,
      cars: 4,
      bridge: { site: 'ponte-sao-joao', deck_m: 66, span: [[41.13501, -8.60143], [41.14540, -8.58631]] },
      path: CP_NORTE,
      source: 'OSM Linha do Norte (Via Ascendente) across the Ponte de São João to Campanhã (ways 142939380, 1207413417, 543213029 + approaches); deck 66 m (dimensions.json ponte-sao-joao)',
    },
    {
      id: 'cp-urbano',
      operator: 'CP Urbanos do Porto',
      line: 'Urbano',
      service: 'urbano',
      colour: '#2E8B57',
      speed_mps: 16,
      count: 1,
      cars: 3,
      bridge: { site: 'ponte-sao-joao', deck_m: 66, span: [[41.13501, -8.60143], [41.14540, -8.58631]] },
      path: CP_NORTE,
      source: 'CP Urbanos do Porto sharing the Linha do Norte alignment across the Ponte de São João; deck 66 m (dimensions.json ponte-sao-joao)',
    },
  ],
  source: 'OSM relation 2567504 (Metro Linha D) and Linha do Norte ways; ODbL, OpenStreetMap contributors',
};

function validateRail(r) {
  if (!Array.isArray(r.items) || !r.items.length) throw new Error('rail: no items');
  for (const it of r.items) {
    if (!['metro', 'mainline', 'urbano'].includes(it.service)) throw new Error(`rail: ${it.id} bad service`);
    if (!Array.isArray(it.path) || it.path.length < 2) throw new Error(`rail: ${it.id} path needs >= 2 points`);
    if (!(it.speed_mps > 0)) throw new Error(`rail: ${it.id} speed must be > 0`);
    if (!(it.count >= 1)) throw new Error(`rail: ${it.id} count must be >= 1`);
    if (!it.bridge?.site || !(it.bridge.deck_m > 0)) throw new Error(`rail: ${it.id} needs bridge {site, deck_m}`);
    for (const q of it.bridge.span ?? []) {
      if (!(q[0] > 41.0 && q[0] < 41.3 && q[1] > -8.8 && q[1] < -8.4)) throw new Error(`rail: ${it.id} bridge span off Porto`);
    }
    for (const q of it.path) {
      if (!(q[0] > 41.0 && q[0] < 41.3 && q[1] > -8.8 && q[1] < -8.4)) throw new Error(`rail: ${it.id} point off Porto`);
    }
  }
  const byService = (s) => r.items.filter((it) => it.service === s).length;
  r.counts = {
    services: r.items.length,
    consists: r.items.reduce((n, it) => n + it.count, 0),
    metro: byService('metro'),
    mainline: byService('mainline'),
    urbano: byService('urbano'),
  };
  return r;
}

// Teleférico de Gaia: lower (Cais de Gaia) -> upper (Jardim do Morro).
const CABLE_STATIONS = { lower: [41.137344, -8.616077], upper: [41.137887, -8.609746] };
const CABLE_LINE = [
  [41.137887, -8.609746], [41.137878, -8.60985], [41.137479, -8.614531], [41.137351, -8.615989], [41.137344, -8.616077],
];

// ---- river traffic (authored over the real channel; see smoke-life.mjs)
// A rabelo run along the Ribeira wall, past the Luís I bridge.
const RABELO_PATH = [
  [41.141, -8.60061], [41.14088, -8.60508], [41.1396, -8.6095], [41.13901, -8.61296],
  [41.1391, -8.61712], [41.14216, -8.62333],
];
// A cruiser line down the Douro to the Foz, under the Arrábida.
const FOZ_PATH = [
  [41.14088, -8.60508], [41.13901, -8.61296], [41.1391, -8.61712], [41.14216, -8.62333],
  [41.14446, -8.63143], [41.14634, -8.63521], [41.1471, -8.63733], [41.1473, -8.6385],
  [41.14735, -8.63962], [41.14718, -8.64147], [41.14642, -8.64672], [41.14537, -8.65129],
];
// A cruiser line up river toward Freixo.
const FREIXO_PATH = [
  [41.14088, -8.60508], [41.14104, -8.60144], [41.141, -8.60061], [41.141, -8.598],
  [41.13856, -8.59401], [41.13901, -8.59033], [41.14031, -8.58766], [41.14172, -8.58254],
];
// The Gaia <-> Ribeira crossing (roughly north-south off the Ribeira).
const FERRY_PATH = [
  [41.14, -8.6125], [41.13945, -8.6123], [41.13885, -8.6124], [41.1383, -8.6125],
];
// A barco-hotel running the same Douro reach as the Foz cruisers.
const HOTEL_PATH = FOZ_PATH;

const BOATS = {
  name: 'River traffic on the Douro',
  items: [
    { id: 'rabelo-1', type: 'rabelo', speed_mps: 3.2, phase: 0.0, sail: true, path: RABELO_PATH },
    { id: 'rabelo-2', type: 'rabelo', speed_mps: 3.2, phase: 0.34, sail: true, path: RABELO_PATH },
    { id: 'rabelo-3', type: 'rabelo', speed_mps: 3.2, phase: 0.67, sail: true, path: RABELO_PATH },
    { id: 'rabelo-4', type: 'rabelo', speed_mps: 3.0, phase: 0.16, sail: true, path: RABELO_PATH },
    { id: 'rabelo-5', type: 'rabelo', speed_mps: 3.4, phase: 0.82, sail: false, path: RABELO_PATH },
    { id: 'cruiser-foz-1', type: 'cruiser', speed_mps: 4.8, phase: 0.0, path: FOZ_PATH },
    { id: 'cruiser-foz-2', type: 'cruiser', speed_mps: 4.8, phase: 0.5, path: FOZ_PATH },
    { id: 'cruiser-freixo-1', type: 'cruiser', speed_mps: 4.6, phase: 0.2, path: FREIXO_PATH },
    { id: 'hotel-1', type: 'hotel', speed_mps: 3.6, phase: 0.72, path: HOTEL_PATH },
    { id: 'ferry-1', type: 'ferry', speed_mps: 4.0, phase: 0.1, path: FERRY_PATH },
  ],
  moored: [
    { type: 'rabelo', p: [41.138, -8.6165], yaw: 100, sail: false },
    { type: 'rabelo', p: [41.13785, -8.6168], yaw: 80, sail: false },
    { type: 'rabelo', p: [41.13815, -8.6145], yaw: 95, sail: false },
    { type: 'rabelo', p: [41.1399, -8.612], yaw: -90, sail: false },
    { type: 'rabelo', p: [41.137925, -8.61665], yaw: 92, sail: false },
    { type: 'rabelo', p: [41.138, -8.61565], yaw: 88, sail: false },
    { type: 'cruiser', p: [41.139025, -8.61325], yaw: -90 },
  ],
  source: 'Authored over the OSM Douro channel / quays (ODbL, OpenStreetMap contributors)',
};

function validateBoats(b) {
  for (const it of b.items) {
    if (!['rabelo', 'cruiser', 'ferry', 'hotel'].includes(it.type)) throw new Error(`boats: bad type ${it.type}`);
    if (!Array.isArray(it.path) || it.path.length < 2) throw new Error(`boats: ${it.id} path needs >= 2 points`);
    if (!(it.speed_mps > 0)) throw new Error(`boats: ${it.id} speed must be > 0`);
    for (const q of it.path) if (!(q[0] > 41.0 && q[0] < 41.3 && q[1] > -8.8 && q[1] < -8.4)) throw new Error(`boats: ${it.id} point off the Douro`);
  }
  for (const m of b.moored) {
    if (!['rabelo', 'cruiser', 'ferry', 'hotel'].includes(m.type)) throw new Error(`boats: bad moored type ${m.type}`);
    if (!Array.isArray(m.p) || m.p.length !== 2) throw new Error('boats: moored point must be [lat, lon]');
  }
  const byType = (t) => b.items.filter((it) => it.type === t).length;
  b.counts = { rabelo: byType('rabelo'), cruiser: byType('cruiser'), ferry: byType('ferry'), hotel: byType('hotel'), moored: b.moored.length };
  return b;
}

// Offset a line laterally by offM with a sin() ramp: 0 at both ends, max at
// the middle. Turns Guindais' single track into the passing loop.
function offsetTrack(center, offM) {
  const kx = M_PER_DEG_LON * cos0;
  const kz = M_PER_DEG_LAT;
  const m = center.map((p) => ({ x: (p[1] - ORIGIN.lon) * kx, z: -(p[0] - ORIGIN.lat) * kz }));
  const cum = [0];
  for (let i = 1; i < m.length; i++) cum.push(cum[i - 1] + Math.hypot(m[i].x - m[i - 1].x, m[i].z - m[i - 1].z));
  const total = cum[cum.length - 1] || 1;
  const out = [];
  for (let i = 0; i < m.length; i++) {
    const p0 = m[Math.max(0, i - 1)];
    const p1 = m[Math.min(m.length - 1, i + 1)];
    let dx = p1.x - p0.x;
    let dz = p1.z - p0.z;
    const l = Math.hypot(dx, dz) || 1;
    dx /= l;
    dz /= l;
    const f = Math.sin(Math.PI * (cum[i] / total));
    out.push([r6(ORIGIN.lat - (m[i].z + dx * offM * f) / kz), r6(ORIGIN.lon + (m[i].x - dz * offM * f) / kx)]);
  }
  return out;
}

const tracks = [offsetTrack(FUN_CENTER, 1.4), offsetTrack(FUN_CENTER, -1.4)];
const spanM = Math.round(length(CABLE_LINE));

const out = {
  generated: new Date().toISOString().slice(0, 10),
  sources: {
    funicular: 'OSM Overpass railway=funicular (Guindais), chained; passing-loop tracks generated with a +-1.4 m lateral ramp',
    tram: 'OSM Overpass relation 6077696 (STCP Tram 1 Infante <-> Passeio Alegre), chained and decimated to 25 m',
    cablecar: 'OSM Overpass aerialway=gondola/station (Teleférico de Gaia); height gain ~60 m from terrain',
    rail: 'OSM route relation 2567504 (Metro do Porto Linha D across the Luís I upper deck) and OSM Linha do Norte ways across the Ponte de São João to Campanhã; bridge deck heights from data/dimensions.json',
    license: 'ODbL, OpenStreetMap contributors',
  },
  funicular: {
    name: 'Funicular dos Guindais (1891, rebuilt 2004)',
    site: null,
    tracks,
    centerline: FUN_CENTER,
    lengths_m: tracks.map((tr) => Math.round(length(tr))),
    stations: { lower: FUN_CENTER[FUN_CENTER.length - 1], upper: FUN_CENTER[0] },
  },
  trams: {
    name: 'Eletrico historico STCP: Linhas 1, 18, 22',
    routes: [
      { id: '1', name: 'Eletrico Linha 1: Infante <-> Passeio Alegre', colour: '#187EC2', relation: 6077696, points: TRAM_1 },
      { id: '18', name: 'Eletrico Linha 18: Clerigos <-> Passeio Alegre', colour: '#2E8B57', relation: 15867094, points: TRAM_18 },
      { id: '22', name: 'Eletrico Linha 22: Carmo <-> Batalha', colour: '#B23A2E', relation: 2772495, points: TRAM_22 },
    ],
    rail_gauge_m: 1.435,
    rail_width_m: 0.07,
    rail_height_m: 0.045,
    speed_mps: 6,
    source: 'STCP historic tram route relations, OSM 6077696 (1), 15867094 (18), 2772495 (22)',
  },
  cablecar: {
    name: 'Teleférico de Gaia (2011)',
    stations: [CABLE_STATIONS.lower, CABLE_STATIONS.upper],
    cabins: 6,
    period: 20,
    span_m: spanM,
    gain_m: 60,
    line: CABLE_LINE,
  },
  boats: validateBoats(BOATS),
  rail: validateRail(RAIL),
  fountains: [],
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(out, null, 1) + '\n');
console.log(
  `data/life.json: ${tracks.length} funicular tracks (${out.funicular.lengths_m.join(', ')} m), ` +
    `${out.trams.routes.length} tram lines (${out.trams.routes.map((r) => `${r.id}: ${Math.round(length(r.points))} m`).join(', ')}), ` +
    `cable car ${spanM} m span, ${out.cablecar.cabins} cabins, ` +
    `${out.rail.items.length} rail services (${out.rail.items.map((r) => `${r.id}: ${Math.round(length(r.path))} m x${r.count}`).join(', ')})`,
);
