// Merge authored landmark fragments into the runtime data and locales.
//
// Content agents write, per landmark id, three small files:
//   data/new/<id>.landmark.json  the landmarks.json fields (name, year, texts…)
//   data/new/<id>.en.json        English translation record
//   data/new/<id>.pt.json        Portuguese translation record
//
// This script folds them into:
//   data/landmarks.json                    (keeps lat/lon/category/model/osm
//                                           from the provisional base; adds the
//                                           authored fields; clears _provisional)
//   src/locales/en.porto.js                ({ landmarks, routes })
//   src/locales/pt.porto.js
//
// Node 22, no deps.  node scripts/merge-content.mjs [--city porto] [--dry-run]
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { CITY, ROOT, dataPath, dataRel } from './city-lib.mjs';

const DRY = process.argv.includes('--dry-run');
const NEW_DIR = join(ROOT, CITY.data_dir, 'new');
const LANDMARKS = CITY.landmarksPath;
const read = (f) => JSON.parse(readFileSync(f, 'utf8'));
const readIf = (f) => (existsSync(f) ? read(f) : null);

const base = existsSync(LANDMARKS) ? read(LANDMARKS) : [];
if (!base.length) throw new Error(`no ${dataRel('landmarks.json')} to merge into`);

const ids = base.map((l) => l.id);
const authored = [];
const en = {};
const pt = {};

for (const id of ids) {
  const lm = readIf(join(NEW_DIR, `${id}.landmark.json`));
  if (!lm) continue;
  authored.push(id);
  const credit = lm.image_credit || null;
  Object.assign(base[base.findIndex((l) => l.id === id)], {
    ...lm,
    // data.js expects objects with url/title and gallery items with src/kind/credit
    sources: (Array.isArray(lm.sources) ? lm.sources : []).map((s) => (typeof s === 'string' ? { title: s, url: s } : s)),
    gallery: (Array.isArray(lm.gallery) ? lm.gallery : []).map((g) => ({
      src: g.src || g.img || '',
      kind: g.kind || 'exterior',
      caption_ru: g.caption_ru || '',
      credit: g.credit || credit,
    })),
  }, { _provisional: false });
  const e = readIf(join(NEW_DIR, `${id}.en.json`));
  const p = readIf(join(NEW_DIR, `${id}.pt.json`));
  if (e) en[id] = e;
  if (p) pt[id] = p;
}

// routes: data/new/routes.<lang>.json -> locales + data/routes.json
const routesBase = readIf(dataPath('routes.json'));
const routesEn = readIf(join(NEW_DIR, 'routes.en.json'));
const routesPt = readIf(join(NEW_DIR, 'routes.pt.json'));

const header = `// Generated by scripts/merge-content.mjs — do not edit by hand.\n`;
const emit = (records, routes) =>
  `${header}export const landmarks = ${JSON.stringify(records, null, 2)};\n\nexport const routes = ${JSON.stringify(routes || {}, null, 2)};\n`;

if (DRY) {
  console.log(`authored ${authored.length}/${ids.length}: ${authored.join(', ') || '(none)'}`);
  process.exit(0);
}

writeFileSync(LANDMARKS, JSON.stringify(base, null, 2) + '\n');
writeFileSync(join(ROOT, 'src', 'locales', 'en.porto.js'), emit(en, routesEn));
writeFileSync(join(ROOT, 'src', 'locales', 'pt.porto.js'), emit(pt, routesPt));

const untranslated = ids.filter((id) => authored.includes(id) && (!en[id] || !pt[id]));
console.log(`merged ${authored.length} landmark(s) into ${dataRel('landmarks.json')} and locales`);
if (untranslated.length) console.warn(`no en/pt for: ${untranslated.join(', ')}`);
